blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path("", views.index, name="index"),
    path('blog/detail/<int:blog_id>',views.blog_detail,name='blog_detail'),
    path('blog/pub',views.pub_blog,name='pub_blog'),
    path('blog/comment/pub',views.pub_comment,name='pub_comment'),
    path('search',views.search,name='search'),
]

zhiliaoblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('blog.urls')),
    path('auth/',include('zlauth.urls'))
]

zlauth/urls.py
from django.urls import path
from . import views
app_name = 'zlauth'
urlpatterns = [
    path('login',views.zllogin,name='login'),
    path('register',views.register,name='register'),
    path('captcha',views.send_email_captcha,name='email_captcha'),
    path('logout',views.zllogout,name='logout'),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
User=get_user_model()
# Create your models here.
class BlogCatalogue(models.Model):
    name=models.CharField(max_length=200,verbose_name='分类名称')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='博客分类'
        verbose_name_plural=verbose_name
class Blog(models.Model):
    title=models.CharField(max_length=200,verbose_name='标题')
    content=models.TextField(verbose_name='内容')
    pub_time=models.DateTimeField(auto_now_add=True,verbose_name='发布时间')
    category=models.ForeignKey(BlogCatalogue,on_delete=models.CASCADE,verbose_name='分类')
    author=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='博客'
        verbose_name_plural=verbose_name
        ordering=['-pub_time']

class BlogComment(models.Model):
    content=models.TextField(verbose_name='内容')
    pub_time=models.DateTimeField(auto_now_add=True,verbose_name='发布时间')
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='comments',verbose_name='所属博客')
    author=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name='评论'
        verbose_name_plural=verbose_name
        ordering=['-pub_time']

zlauth/models.py
from django.db import models

# Create your models here.
class CaptchaModel(models.Model):
    email=models.EmailField(unique=True)
    captcha=models.CharField(max_length=4)
    create_time=models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
class PubBlogForm(forms.Form):
    title=forms.CharField(max_length=200,min_length=2)
    content=forms.CharField(min_length=2)
    category=forms.IntegerField()

zlauth/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import CaptchaModel
User=get_user_model()
class RegisterForm(forms.Form):
    username=forms.CharField(max_length=20,min_length=2,error_messages={'required':'请传入用户名',"max_length":'用户名长度在2-20之间',"min_length":'用户名长度在2-20之间'})

    email=forms.EmailField(error_messages={"required":'请输入邮箱','invalid':"请输入正确邮箱"})
    captcha=forms.CharField(max_length=4,min_length=4)
    password=forms.CharField(max_length=20,min_length=6)

    def clean_email(self):
        email=self.cleaned_data.get('email')
        exists=User.objects.filter(email=email).exists()
        if exists:
            raise forms.ValidationError('邮箱注册')
        return email
    def clean_captcha(self):
        captcha = self.cleaned_data.get('captcha')
        email=self.cleaned_data.get('email')
        captcha_model=CaptchaModel.objects.filter(email=email,captcha=captcha).first()
        if not captcha_model:
            raise forms.ValidationError("验证码邮箱不匹配")
        captcha_model.delete()
        return captcha_model

class LoginForm(forms.Form):
    email = forms.EmailField(error_messages={"required": '请输入邮箱', 'invalid': "请输入正确邮箱"})
    # captcha = forms.CharField(max_length=4, min_length=4)
    password = forms.CharField(max_length=20, min_length=6)
    remember = forms.BooleanField(required=False)

blog/views.py
from django.shortcuts import render,reverse,redirect
from django.urls.base import reverse_lazy
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods,require_POST,require_GET
from .models import BlogCatalogue,Blog,BlogComment
from .forms import PubBlogForm
from django.db.models import Q
# Create your views here.
def index(request):
    blogs=Blog.objects.all()
    return render(request,'index.html',context={'blogs':blogs})

def blog_detail(request,blog_id):
    try:
        blog=Blog.objects.get(pk=blog_id)
    except Exception as e:
        blog=None
    return render(request,'blog_detail.html',context={'blog':blog})
@require_http_methods(['GET','POST'])
@login_required()
def pub_blog(request):
    if request.method == "GET":
        categories = BlogCatalogue.objects.all()
        return render(request,'pub_blog.html',context={'categories':categories})
    else:
        form=PubBlogForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content=form.cleaned_data.get('content')
            category_id=form.cleaned_data.get('category')
            blog=Blog.objects.create(title=title,content=content,category_id=category_id,author=request.user)
            return JsonResponse({"code":200,"message":"博客发布成功","data":{"blog_id":blog.id}})

        else:
            print(form.errors)
            return JsonResponse({"code":400,'message':"参数错误"})

@require_POST
@login_required()
def pub_comment(request):
    blog_id=request.POST.get('blog_id')
    content=request.POST.get('content')
    BlogComment.objects.create(content=content,blog_id=blog_id,author=request.user)
    return redirect(reverse("blog:blog_detail",kwargs={'blog_id':blog_id}))

def search(request):
    q=request.GET.get('q')
    blogs=Blog.objects.filter(Q(title__icontains=q)|Q(content__icontains=q)).all()
    return render(request,'index.html',context={'blogs':blogs})

zlauth/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect,reverse
import string
import random
from django.core.mail import send_mail
from .models import CaptchaModel
from django.views.decorators.http import require_http_methods
from .forms import RegisterForm,LoginForm
from django.contrib.auth import get_user_model,login,logout
from django.views.decorators.csrf import csrf_exempt
User=get_user_model()

# Create your views here.
@csrf_exempt
@require_http_methods(['GET','POST'])
def zllogin(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        form=LoginForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data.get('email')
            password=form.cleaned_data.get('password')
            remember=form.cleaned_data.get('remember')
            user=User.objects.filter(email=email).first()
            if user and user.check_password(password):
                login(request,user)
                if not remember:
                    request.session.set_expiry(0)
                return redirect('/')
            else:
                print('邮箱错误')
                # form.add_error(email,'邮箱密码')
                # return render(request, 'login.html',context={"form":form})
                return redirect(reverse('zlauth:login'))



@require_http_methods(['GET', 'POST'])
def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        form=RegisterForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data.get('email')
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            User.objects.create_user( email=email,username=username, password=password)
            return redirect(reverse('zlauth:login'))
        else:
            print(form.errors)
            return redirect(reverse('zlauth:register'))
            # return render(request, 'register.html', {'form': form})



# def register(request):
#     return render(request, 'register.html')


def send_email_captcha(request):
    email = request.GET.get('email')
    if not email:
        return JsonResponse({"code": 400, "message": "必须传递邮箱"})
    captcha = "".join(random.sample(string.digits, 4))
    CaptchaModel.objects.update_or_create(email=email, defaults={'captcha': captcha})
    send_mail("知了博客注册", message=f"您的注册验证码:{captcha}", recipient_list=[email], from_email=None)
    return JsonResponse({"code":200,"message":"邮箱验证码"})

def zllogout(request):
    logout(request)
    return redirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-知了博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}
    	
    {% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height="40">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>

            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="GET">
                <input type="search" name="q" class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
            {% if user.is_authenticated %}
                <div class="dropdown text-end"><a href="#"
                                                  class="d-block link-body-emphasis text-decoration-none dropdown-toggle show"
                                                  data-bs-toggle="dropdown" aria-expanded="true"> <img
                        src="{% static 'image/avatar.webp' %}" alt="mdo" width="32" height="32" class="rounded-circle"> </a>
                    <ul class="dropdown-menu text-small show" data-popper-placement="top-start"
                        style="position: absolute; inset: auto auto 0px 0px; margin: 0px; transform: translate3d(0px, -34px, 0px);">
                        
                        <li><a class="dropdown-item" href="{% url 'zlauth:logout' %}">退出登录</a></li>
                    </ul>
                </div>
                {% else %}
                <div class="text-end">
                <a href="{% url 'zlauth:login' %}"  type="button" class="btn btn-outline-primary me-2">登录</a>
                <a href="{% url 'zlauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
            {% endif%}
            
            
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

templates/blog_detail.html
{#{% extends 'base.html' %}#}
{#{% block head %}#}
{#        <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">#}
{#    <script src="{% static 'highlight/highlight.min.js' %}"></script>#}
{##}
{#{% endblock %}#}
{#{% block main %}#}
{#    #}
{#     <h1>{{ blog.title }}</h1>#}
{#    <hr>#}
{##}
{#    <div class="mt-2">#}
{#        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="30" width="30" alt="">#}
{#        <span class="ms-2">{{ blog.author.username }}</span>#}
{#        <span class="ms-2">于</span>#}
{#        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分" }}</span>发布#}
{#    </div>#}
{#    <hr>#}
{#    <div class="py-2">#}
{#        {{ blog.content|safe }}#}
{#    </div>#}
{#    #}
{#    <hr>#}
{#    <div class="mt-2">#}
{#        <h3>评论(10)</h3>#}
{#        <form action="{% url 'blog:pub_comment' %}" method="POST">#}
{#            {% csrf_token %}#}
{#            <input type="hidden" name="blog_id" value="{{ blog.id }}">#}
{#            <div class="mt-2">#}
{#                <input type="text" class="form-control" placeholder="请输入评论" name="content">#}
{##}
{#            </div>#}
{#            <div class="text-end mt-2">#}
{#                <button type="button" class="btn btn-primary">评论</button>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}
{#    <div class="mt-2">#}
{#        <ul class="list-group">#}
{#            <li class="list-group-item mb-2">#}
{#                <div class="d-flex justify-content-between text-body-secondary">#}
{#                    <div class="user-info">#}
{#                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="40" width="40" alt="">#}
{#                        <span class="ms-2">知了课堂</span>#}
{#                    </div>#}
{#                    <div class="create-time" style="line-height: 40px;">2024.3.29 11:12</div>#}
{#                </div>#}
{#                 <div class="mt-2">这是评论内容</div>#}
{#            </li>#}
{#              <li class="list-group-item mb-2">#}
{#                <div class="d-flex justify-content-between text-body-secondary">#}
{#                    <div class="user-info">#}
{#                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="40" width="40" alt="">#}
{#                        <span class="ms-2">知了课堂</span>#}
{#                    </div>#}
{#                    <div class="create-time" style="line-height: 40px;">2024.3.29 11:12</div>#}
{#                </div>#}
{#                 <div class="mt-2">这是评论内容</div>#}
{#            </li>#}
{##}
{#        </ul>#}
{#    </div>#}
{#   #}
{#{% endblock %}#}


{#{% extends 'base.html' %}#}
{##}
{#{% block head %}#}
{#    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/default.min.css">#}
{#<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js"></script>#}
{#    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">#}
{#    <script src="{% static 'highlight/highlight.min.js' %}"></script>#}
{#    <style>pre code {#}
{#    white-space: pre-wrap;#}
{#    word-break: break-word;#}
{##}
{#</style>#}
{#    <script>hljs.configure({useBR: true});</script>#}
{#    <style>#}
{#    div.py-2 {#}
{#  white-space: pre;#}
{##}
{#    </style>#}
{#   #}
{##}
{#{% endblock %}#}
{##}
{#{% block main %}#}
{#	<h1>{{ blog.title }}</h1>#}
{#    <hr>#}
{#    <div class="mt-2">#}
{#        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="30" height="30" alt="">#}
{#        <span class="ms-2">{{ blog.author.username }}</span>#}
{#        <span class="ms-2">于</span>#}
{#        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分" }}</span>发布#}
{#    </div>#}
{#    <hr>#}
{#    <div class="py-2">#}
{#        {{ blog.content|safe }}#}
{##}
{#    </div>#}
{#    <pre><code class="language-python">#}
{#def add(a, b):#}
{#    return a + b#}
{#</code></pre>#}
{##}
{#   #}
{##}
{#    <hr>#}
{#    <div class="mt-2">#}
{#        <h3>评论（{{ blog.comments.all|length }}）</h3>#}
{#        <form action="{% url 'blog:pub_comment' %}" method="POST">#}
{#            {% csrf_token %}#}
{#            <input type="hidden" name="blog_id" value="{{ blog.id }}">#}
{#            <div class="mt-2">#}
{#                <input type="text" class="form-control" placeholder="请输入评论" name="content">#}
{#            </div>#}
{#            <div class="text-end mt-2">#}
{#                <button type="submit" class="btn btn-primary">评论</button>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}
{#    <div class="mt-2">#}
{#        <ul class="list-group list-group-flush">#}
{#            {% for comment in blog.comments.all %}#}
{#                <li class="list-group-item">#}
{#                  <div class="d-flex justify-content-between text-body-secondary">#}
{#                      <div class="user-info">#}
{#                          <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="40" height="40" alt="">#}
{#                          <span class="ms-2">{{ comment.author.username }}</span>#}
{#                      </div>#}
{#                      <div class="create-time" style="line-height: 40px;">{{ comment.pub_time|date:"Y年m月d日 h时i分" }}</div>#}
{#                  </div>#}
{#                  <div class="mt-2">{{ comment.content }}</div>#}
{#              </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    </div>#}
{#    <script>#}
    {#hljs.configure({useBR: true});#}
{#    hljs.highlightAll();#}
{#    </script>#}
{#{% endblock %}#}






{% extends 'base.html' %}

{% block head %}
{#    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">#}
{#    <script src="{% static 'highlight/highlight.min.js' %}"></script>#}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js"></script>

<script>
  hljs.highlightAll();
</script>
{% endblock %}

{% block main %}
	<h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="30" height="30" alt="">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_time|date:"Y年m月d日 h时i分" }}</span>发布
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>评论（{{ blog.comments.all|length }}）</h3>
        <form action="{% url 'blog:pub_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                  <div class="d-flex justify-content-between text-body-secondary">
                      <div class="user-info">
                          <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" width="40" height="40" alt="">
                          <span class="ms-2">{{ comment.author.username }}</span>
                      </div>
                      <div class="create-time" style="line-height: 40px;">{{ comment.pub_time|date:"Y年m月d日 h时i分" }}</div>
                  </div>
                  <div class="mt-2">{{ comment.content }}</div>
              </li>
            {% endfor %}
        </ul>
    </div>
    <script>
    hljs.highlightAll();
    </script>
{% endblock %}

templates/html/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height="40">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">发布博客</a></li>

            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
            <div class="text-end">
                <button type="button" class="btn btn-outline-primary me-2">登录</button>
                <button type="button" class="btn btn-primary">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <h1>Django课程详情</h1>
    <hr>

    <div class="mt-2">
        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="30" width="30" alt="">
        <span class="ms-2">知了课堂</span>
        <span class="ms-2">于</span>
        <span class="ms-2">2025/3/29 15:22</span>发布
    </div>
    <hr>
    <div class="py-2">
        这是博客详情
    </div>
    
    <hr>
    <div class="mt-2">
        <h3>评论(10)</h3>
        <form action="" method="POST">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="请输入评论">

            </div>
            <div class="text-end mt-2">
                <button type="button" class="btn btn-primary">评论</button>
            </div>
        </form>
    </div>
    <div class="mt-2">
        <ul class="list-group">
            <li class="list-group-item mb-2">
                <div class="d-flex justify-content-between text-body-secondary">
                    <div class="user-info">
                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="40" width="40" alt="">
                        <span class="ms-2">知了课堂</span>
                    </div>
                    <div class="create-time" style="line-height: 40px;">2024.3.29 11:12</div>
                </div>
                 <div class="mt-2">这是评论内容</div>
            </li>
              <li class="list-group-item mb-2">
                <div class="d-flex justify-content-between text-body-secondary">
                    <div class="user-info">
                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="40" width="40" alt="">
                        <span class="ms-2">知了课堂</span>
                    </div>
                    <div class="create-time" style="line-height: 40px;">2024.3.29 11:12</div>
                </div>
                 <div class="mt-2">这是评论内容</div>
            </li>

        </ul>
    </div>
   
</main>
</body>
</html>

templates/html/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height="40">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">发布博客</a></li>

            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
            <div class="text-end">
                <button type="button" class="btn btn-outline-primary me-2">登录</button>
                <button type="button" class="btn btn-primary">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <h1>博客列表</h1>
    <div class="row row-cols-2 row-gap-4">
        <div class="col">
            <div class="card ">
                <div class="card-header">
                    <a href="#">Django零基础到项目实战</a>
                </div>
                <div class="card-body" style="height: 100px;">
                    
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/avatar.webp' %}" class="rounded-circle" height="30" width="30" alt="">
                        知了课堂
                    </div>
                    <div>发布时间:2025/7/20</div>
                </div>
            </div>

        </div>
       
    </div>
</main>
</body>
</html>

templates/html/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>知了博客</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/logo.png' %}" alt="" height="40">
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">发布博客</a></li>

            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
            <div class="text-end">
                <button type="button" class="btn btn-outline-primary me-2">登录</button>
                <button type="button" class="btn btn-primary">注册</button>
            </div>
        </div>
    </div>
</header>
<main class="container bg-white p-3 rounded">
    <div style="max-width: 330px;" class="m-auto">
        <h1>登录</h1>
        <form action="" method="POST">
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" name='email' class="form-control" placeholder="邮箱">
            </div>


            <div class="mb-3">
                <label>密码</label>
                <input type="password" name='password' class="form-control" placeholder="密码">
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
                
                
                
            </div>
            
            
            <div class="mb-3">
                <button class="btn btn-primary w-100">立即登录</button>
            </div>


        </form>
    </div>
</main>
</body>
</html>